---
- name: Converge
  hosts: all
  become: true
  tasks:
    # Basically telling molecule to pretend that the name of the role is whatever the name
    # Of the directory is
    - name: Include role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
