---
name: CI
"on":
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 15 * *"
  workflow_dispatch:

defaults:
  run:
    working-directory: "raveshaww.kubeadm_setup"

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  molecule:
    name: Molecule
    uses: ./.github/workflows/molecule.yml
    needs: [lint]
